---
# External collections
collections:
  - ansible.posix
  - community.general
  - community.docker

# External roles
roles:
  # Docker
  - name: geerlingguy.docker
  
  # Development tools
  - name: gantsign.visual-studio-code
  - name: geerlingguy.git 