---
# Handlers for Kafka role

- name: Restart zookeeper
  ansible.builtin.systemd:
    name: zookeeper
    state: restarted
    daemon_reload: true

- name: Restart kafka
  ansible.builtin.systemd:
    name: kafka
    state: restarted
    daemon_reload: true 