---
- name: Verify
  hosts: all
  become: true
  pre_tasks:
    - name: include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../defaults/main.yml"
  tasks:
    - name: include tasks
      ansible.builtin.import_tasks: "{{ playbook_dir }}/../../tests/tasks/post.yml"
