---
- name: Setup Altilar Linux Workstation
  hosts: workstations
  become: true
  gather_facts: true
  
  roles:
    - common
    - dev_tools
  
  tasks:
    - name: Ensure system is up to date
      ansible.builtin.debug:
        msg: "This is a placeholder task. Add actual tasks here." 