---
- name: Setup Altilar Linux Workstation
  hosts: workstations
  become: true
  gather_facts: true # Gather facts at the beginning

  roles:
    # Basic tools
    - role: common
      tags: ['common', 'basic']
    
    # Shell setup with ZSH and Oh My Zsh
    - role: zsh
      tags: ['zsh', 'shell', 'basic']
    
    # Developer tools
    - role: dev_tools
      tags: ['dev', 'tools']
    
    # Diagnostic tools
    - role: diagnostic_tools
      tags: ['diagnostic', 'tools']
    
    # Docker (no sudo)
    - role: docker_no_sudo
      tags: ['docker', 'container']
    
    # Node.js via NVM (using our custom role instead of Galaxy role)
    - role: nvm
      tags: ['node', 'javascript', 'web']
      vars:
        nvm_user: "{{ ansible_user }}" # Explicitly pass the user
    
    # Golang via GVM
    - role: gvm
      tags: ['go', 'golang']
  
  tasks:
    - name: Ensure system is up to date
      ansible.builtin.debug:
        msg: "This is a placeholder task. Add actual tasks here." 